<?php require_once('constants.php');
	  require_once('../db/conn.php');
?>
<html>
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
		<?php echo $this->headTitle($this->title); ?>
		<script type="text/javascript">baseUrl = '<?php echo $this->baseUrl(); ?>';</script>

		<!-- CSS -->		
		<link rel="stylesheet" type="text/css" href="<?php echo CSS; ?>/layout.css" />
		<link rel="stylesheet" type="text/css" href="<?php echo CSS; ?>/bootstrap.css" />
		<link rel="stylesheet" type="text/css" href="<?php echo CSS; ?>/bootstrap-theme.min.css">
		
		<!-- JS -->
		<script type="text/javascript" src="<?php echo JS; ?>/jquery-1.9.1.js"></script>
		<script type="text/javascript" src="<?php echo JS; ?>/bootstrap.js"></script>
	</head>
	<body>
		<div id="container">
			<header>
				<div id="navigation">
					<nav class="navbar navbar-default" role="navigation">
						<div class="container-fluid">
						    <!-- Brand and toggle get grouped for better mobile display -->
						    <div class="navbar-header">
						      	<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
						        	<span class="sr-only">Toggle navigation</span>
						        	<span class="icon-bar"></span>
						        	<span class="icon-bar"></span>
						        	<span class="icon-bar"></span>
						      	</button>
						      	<a class="navbar-brand" href="<?php echo $this->baseUrl(); ?>">
						      		<img src="<?php echo IMG; ?>/ico128.png" id="logo"/>
						      		DOJOSYS
						      	</a>
						    </div>

						    <!-- Collect the nav links, forms, and other content for toggling -->
						    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
						    	<ul class="nav navbar-nav pull-right">
						    		<li><a href="<?php echo $this->baseUrl(); ?>/admin">Principal</a></li>
						    		<li class="dropdown">
						        		<a href="#" class="dropdown-toggle" data-toggle="dropdown">
						        			Cadastros
						        			<span class="caret"></span>
						        		</a>
						        		<ul class="dropdown-menu" role="menu">
						        			<li>
						        				<a href="<?php echo $this->baseUrl(); ?>/aluno/create">
						        					Atleta
						        				</a>
						        			</li>
						        			<li>
						        				<a href="<?php echo $this->baseUrl(); ?>/admin/graduacao/create">
						        					Graduação
						        				</a>
						        			</li>
						        			<li class="divider"></li>
						        			<li>
						        				<a href="<?php echo $this->baseUrl(); ?>/admin/atividadeesportiva/create">
						        					Atividade Esportiva
						        				</a>
						        			</li>
						        			<li>
						        				<a href="<?php echo $this->baseUrl(); ?>/evento/create">
						        					Evento
						        				</a>
						        			</li>
						        		</ul>
						        	</li>
						        	<li class="dropdown">
						        		<a href="#" class="dropdown-toggle" data-toggle="dropdown">
						        			Análises
						        			<span class="caret"></span>
						        		</a>
						        		<ul class="dropdown-menu" role="menu">
						        			<li>
						        				<a href="<?php echo $this->baseUrl(); ?>/campeonato/analise/modalcreate">
						        					Análise
						        				</a>
						        			</li>
						        			<li>
						        				<a href="<?php echo $this->baseUrl(); ?>/campeonato/analise/modaledit">
						        					Editar Análise
						        				</a>
						        			</li>
						        		</ul>
						        	</li>
						        	<li class="dropdown">
						        		<a href="#" class="dropdown-toggle" data-toggle="dropdown">
						        			Estatísticas
						        			<span class="caret"></span>
						        		</a>
						        		<ul class="dropdown-menu" role="menu">
						        			<li>
						        				<a href="<?php echo $this->baseUrl(); ?>/campeonato/estat/modalgeral">
						        					Estatística Geral
						        				</a>
						        			</li>
						        			<li>
						        				<a href="<?php echo $this->baseUrl(); ?>/campeonato/estat/modalcampeonato">
						        					Estatística x Camp.
						        				</a>
						        			</li>
						        			<li>
						        				<a href="#">
						        					Estatística x Classe/Categ.
						        				</a>
						        			</li>
						        		</ul>
						        	</li>
						        	<li><a href="<?php echo $this->baseUrl(); ?>/index/sobre">Sobre</a>
						        </ul>
						    </div>
						</div>
					</nav>
				</div>
			</header>
			<section>
				<div id="content">
					<div id="content_fields">
						<?php echo $this->layout()->content ?>
					</div>
				</div>
			</section>
		</div>
	</body>
</html>