<script>
  $('#myModal').modal({
    keyboard: false
  })
</script>

<div class="modal fade" id="myModal">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title">Sucesso</h4>
      </div>
      <div class="modal-body">
        <div class="text-center">
          <span class='btn-lg glyphicon glyphicon-ok-sign'></span>
          <h4 class="text-success">Dados Apagados com Sucesso!</h4>
        </div>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->